#!/usr/bin/env bash

set -euo pipefail

export LC_ALL=C

markdown_dir="${1:-docs/api}"
vimdoc_dir="${2:-doc}"

if [[ "$markdown_dir" != "docs/api" || "$vimdoc_dir" != "doc" ]]; then
	echo "The generated API paths must be docs/api and doc" >&2
	exit 1
fi

for command in pandoc perl; do
	if ! command -v "$command" >/dev/null 2>&1; then
		echo "generate_api_vimdoc.sh: required command not found: $command" >&2
		exit 127
	fi
done

if ! pandoc --list-output-formats | grep -Fxq 'vimdoc'; then
	echo "generate_api_vimdoc.sh: installed Pandoc does not support the vimdoc writer" >&2
	exit 1
fi

while IFS= read -r -d '' markdown_file; do
	relative_path="${markdown_file#"$markdown_dir"/}"
	stem="${relative_path%.md}"
	if [[ "$relative_path" == "index.md" ]]; then
		vimdoc_file="$vimdoc_dir/nvim-mybatis-api.txt"
		{
			printf '# nvim-mybatis API\n\n'
			LC_ALL=C perl -0pe \
				's/\[([^\]]+)\]\((types|modules)\/([^)]+)\.md\)/$1 |nvim-mybatis-api-$2-$3|/g' \
				"$markdown_file"
		} | pandoc -f gfm -t vimdoc > "$vimdoc_file"
		LC_ALL=C TAG_PREFIX="nvim-mybatis-api-index-" perl -0pi -e \
			's/\*(?!nvim-mybatis-api\*)([A-Za-z][A-Za-z0-9_.-]*)\*(?=[ \t]*(?:\n|\z))/"*" . $ENV{TAG_PREFIX} . $1 . "*"/gme' \
			"$vimdoc_file"
	else
		vimdoc_file="$vimdoc_dir/nvim-mybatis-api-${stem//\//-}.txt"
		temporary_file="$vimdoc_file.tmp"
		pandoc -f gfm -t vimdoc "$markdown_file" > "$temporary_file"
		help_tag="${vimdoc_file##*/}"
		help_tag="${help_tag%.txt}"
		LC_ALL=C TAG_PREFIX="${help_tag}-" perl -0pi -e \
			's/\*([A-Za-z][A-Za-z0-9_.-]*)\*(?=[ \t]*(?:\n|\z))/"*" . $ENV{TAG_PREFIX} . $1 . "*"/gme' \
			"$temporary_file"
		{
			printf '*%s*\n\n' "$help_tag"
			cat "$temporary_file"
		} > "$vimdoc_file"
		rm -f -- "$temporary_file"
	fi

	{
		printf '\nGenerated by emmylua_doc_cli <https://github.com/CppCXY/emmylua-analyzer-rust>\n'
		printf '\nvim:tw=78:ts=8:noet:ft=help:norl:\n'
	} >> "$vimdoc_file"
done < <(find "$markdown_dir" -type f -name '*.md' -print0 | sort -z)
