local helpers = require("spec.helpers")
local context = require("nvim-mybatis.completion.context")

local XML = "project/src/main/resources/mapper/UserMapper.xml"

describe("completion.context", function()
	after_each(function()
		vim.cmd("%bdelete!")
	end)

	it("detects class context on type attributes", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('resultType="com.example.entity.User"'))
		local ctx = context.detect()
		assert.truthy(ctx)
		assert.equals("class", ctx.kind)
		assert.truthy(ctx.value_node)
	end)

	it("detects class context on the namespace attribute", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('namespace="com.example.mapper.UserMapper"'))
		assert.equals("class", context.detect().kind)
	end)

	it("detects method context on crud tag id attributes", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('id="selectUser"'))
		local ctx = context.detect()
		assert.truthy(ctx)
		assert.equals("method", ctx.kind)
		assert.equals("com.example.mapper.UserMapper", ctx.namespace)
	end)

	it("returns nil for the id attribute of a non-crud tag", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('id="userMap"'))
		assert.is_nil(context.detect())
	end)

	it("detects field context on resultMap property attributes", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('property="username"'))
		local ctx = context.detect()
		assert.truthy(ctx)
		assert.equals("field", ctx.kind)
		assert.equals("com.example.entity.User", ctx.type)
	end)

	it("detects refid context on include refid attributes", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark('refid="baseColumns"'))
		assert.equals("refid", context.detect().kind)
	end)

	it("returns nil outside attribute values", function()
		helpers.load_buf(XML, "xml")
		assert.truthy(helpers.goto_mark("from users"))
		assert.is_nil(context.detect())
	end)
end)
